name: firebase_database_web
description: The web implementation of firebase_database
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_database/firebase_database_web
version: 0.1.0
flutter:
  plugin:
    platforms:
      web:
        pluginClass: DatabaseWeb
        fileName: firebase_database_web.dart
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  firebase: ^9.0.1
  http_parser: ^4.0.0
  meta: ^1.1.7
  firebase_core: ^1.1.0
  firebase_database_platform_interface:
    path: ../firebase_database_platform_interface
  js: ^0.6.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core_platform_interface: ^4.0.0
  firebase_core_web: ^1.0.2
  mockito: ^5.0.14
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.13+hotfix.4 <2.0.0"
