name: firebase_database
description: Flutter plugin for Firebase Database, a cloud-hosted NoSQL database
  with realtime data syncing across Android and iOS clients, and offline access.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_database/firebase_database
version: 3.2.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.database
        pluginClass: FirebaseDatabasePlugin
      ios:
        pluginClass: FLTFirebaseDatabasePlugin
      web:
        default_package: firebase_database_web

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.1.0
  firebase_database_platform_interface:
    git:
      url: https://github.com/XSiyabonga/flutterfire.git
      path: packages/firebase_database/firebase_database_platform_interface
      ref: lastest_web_support
  firebase_database_web:
    git:
      url: https://github.com/XSiyabonga/flutterfire.git
      path: packages/firebase_database/firebase_database_web
      ref: lastest_web_support
dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.3.0
  mockito: ^5.0.14 
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0 <2.0.0"
